#%RAML 1.0 NamedExample
value: |
  {
    "amount": {
      "amount": "8.00",
      "currency": "EUR" 
    },
    "label": "Spotify",
    "receiver_IBAN": "GB29NWBK60161331926000",
    "description": "Spotify"
  }