// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChinookAspNetCore.ChinookV1.Models;

// Do not modify this file. This code was generated by RAML Server Scaffolder

namespace ChinookAspNetCore.ChinookV1
{
    [Route("albums")]
    public partial class AlbumsController : Controller
    {


/// <summary>
		/// /albums
		/// </summary>
		/// <returns>IList&lt;Album&gt;</returns>
        [HttpGet("albums")]
        public virtual IActionResult GetBase()
        {
            // Do not modify this code
                        return  ((IAlbumsController)this).Get();
                    }

/// <summary>
		/// /albums
		/// </summary>
		/// <param name="album"></param>
        [HttpPost("albums")]
        public virtual IActionResult PostBase([FromBody] Models.Album album)
        {
            // Do not modify this code
                        return  ((IAlbumsController)this).Post(album);
                    }

/// <summary>
		/// /albums/{id}
		/// </summary>
		/// <param name="id"></param>
		/// <returns>Album</returns>
        [HttpGet("{id}")]
        public virtual IActionResult GetByIdBase(string id)
        {
            // Do not modify this code
                        return  ((IAlbumsController)this).GetById(id);
                    }

/// <summary>
		/// /albums/{id}
		/// </summary>
		/// <param name="album"></param>
		/// <param name="id"></param>
        [HttpPut("{id}")]
        public virtual IActionResult PutBase([FromBody] Models.Album album,string id)
        {
            // Do not modify this code
                        return  ((IAlbumsController)this).Put(album,id);
                    }

/// <summary>
		/// /albums/{id}
		/// </summary>
		/// <param name="id"></param>
        [HttpDelete("{id}")]
        public virtual IActionResult DeleteBase(string id)
        {
            // Do not modify this code
                        return  ((IAlbumsController)this).Delete(id);
                    }
    }
}
