// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ChinookAspNetCore.ChinookV1.Models
{
    public partial class Invoice
    {
        

        [Required]
        public object Customer { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string InvoiceDate { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string BillingAddress { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string BillingCity { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string BillingState { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string BillingCountry { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string BillingPostalCode { get; set; }

        [Required]
        public IList<InvoiceLine> Lines { get; set; }
    } // end class

} // end Models namespace

