// Template: Models (ApiModel.t4) version 3.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ChinookAspNetCore.ChinookV1.Models
{
    public partial class InvoiceLine
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public int Id { get; set; }

        [Required]
        public object Track { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        [Range(0.00,double.MaxValue)]
        public decimal UnitPrice { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        [Range(1,int.MaxValue)]
        public int Quantity { get; set; }
    } // end class

} // end Models namespace

