// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChinookAspNetCore.ChinookV1.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace ChinookAspNetCore.ChinookV1
{
    [Route("invoices")]
    public partial class InvoicesController : Controller
    {


/// <summary>
		/// /invoices
		/// </summary>
		/// <returns>IList&lt;Invoice&gt;</returns>
        [HttpGet("invoices")]
        public virtual IActionResult GetBase()
        {
            // Do not modify this code
                        return  ((IInvoicesController)this).Get();
                    }

/// <summary>
		/// /invoices
		/// </summary>
		/// <param name="invoice"></param>
        [HttpPost("invoices")]
        public virtual IActionResult PostBase([FromBody] Models.Invoice invoice)
        {
            // Do not modify this code
                        return  ((IInvoicesController)this).Post(invoice);
                    }

/// <summary>
		/// /invoices/{id}
		/// </summary>
		/// <param name="id"></param>
		/// <returns>Invoice</returns>
        [HttpGet("{id}")]
        public virtual IActionResult GetByIdBase(string id)
        {
            // Do not modify this code
                        return  ((IInvoicesController)this).GetById(id);
                    }

/// <summary>
		/// /invoices/{id}
		/// </summary>
		/// <param name="invoice"></param>
		/// <param name="id"></param>
        [HttpPut("{id}")]
        public virtual IActionResult PutBase([FromBody] Models.Invoice invoice,string id)
        {
            // Do not modify this code
                        return  ((IInvoicesController)this).Put(invoice,id);
                    }

/// <summary>
		/// /invoices/{id}
		/// </summary>
		/// <param name="id"></param>
        [HttpDelete("{id}")]
        public virtual IActionResult DeleteBase(string id)
        {
            // Do not modify this code
                        return  ((IInvoicesController)this).Delete(id);
                    }
    }
}
