// Template: Models (ApiModel.t4) version 3.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ChinookAspNetCore.ChinookV1.Models
{
    public partial class Person
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public int Id { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string Title { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string BirthDate { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string LastName { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string Address { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string City { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string State { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string Country { get; set; }

        [MaxLength(14)]
        [MinLength(4)]
        public string PostalCode { get; set; }

        [MaxLength(0)]
        [MinLength(8)]
        public string Phone { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string Fax { get; set; }

        [MaxLength(0)]
        [MinLength(0)]
        public string Email { get; set; }


        public byte[] Picture { get; set; }
    } // end class

} // end Models namespace

