// Template: Models (ApiModel.t4) version 3.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ChinookAspNetCore.ChinookV1.Models
{
    public partial class Track
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public int Id { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string Name { get; set; }

        [Required]
        public Album Album { get; set; }

        [Required]
        public MediaType MediaType { get; set; }

        [Required]
        public Genre Genre { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string Composer { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public int Milliseconds { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public int Bytes { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public decimal UnitPrice { get; set; }
    } // end class

} // end Models namespace

