// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChinookAspNetCore.ChinookV1.Models;

// Do not modify this file. This code was generated by RAML Server Scaffolder

namespace ChinookAspNetCore.ChinookV1
{
    [Route("tracks")]
    public partial class TracksController : Controller
    {


/// <summary>
		/// /tracks
		/// </summary>
		/// <returns>IList&lt;Track&gt;</returns>
        [HttpGet("tracks")]
        public virtual IActionResult GetBase()
        {
            // Do not modify this code
                        return  ((ITracksController)this).Get();
                    }

/// <summary>
		/// /tracks
		/// </summary>
		/// <param name="track"></param>
        [HttpPost("tracks")]
        public virtual IActionResult PostBase([FromBody] Models.Track track)
        {
            // Do not modify this code
                        return  ((ITracksController)this).Post(track);
                    }

/// <summary>
		/// /tracks/{id}
		/// </summary>
		/// <param name="id"></param>
		/// <returns>Track</returns>
        [HttpGet("{id}")]
        public virtual IActionResult GetByIdBase(string id)
        {
            // Do not modify this code
                        return  ((ITracksController)this).GetById(id);
                    }

/// <summary>
		/// /tracks/{id}
		/// </summary>
		/// <param name="track"></param>
		/// <param name="id"></param>
        [HttpPut("{id}")]
        public virtual IActionResult PutBase([FromBody] Models.Track track,string id)
        {
            // Do not modify this code
                        return  ((ITracksController)this).Put(track,id);
                    }

/// <summary>
		/// /tracks/{id}
		/// </summary>
		/// <param name="id"></param>
        [HttpDelete("{id}")]
        public virtual IActionResult DeleteBase(string id)
        {
            // Do not modify this code
                        return  ((ITracksController)this).Delete(id);
                    }

/// <summary>
		/// /tracks/byartist/{id}
		/// </summary>
		/// <param name="id"></param>
		/// <returns>TracksByArtist</returns>
        [HttpGet("byartist/{id}")]
        public virtual IActionResult GetByartistByIdBase(string id)
        {
            // Do not modify this code
                        return  ((ITracksController)this).GetByartistById(id);
                    }
    }
}
