// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using MoviesWebApiSample.MoviesV1.Models;

// Do not modify this file. This code was generated by RAML Server Scaffolder

namespace MoviesWebApiSample.MoviesV1
{
    [RoutePrefix("search")]
    public partial class SearchController : ApiController
    {


/// <summary>
		/// search movies by name or director - /search
		/// </summary>
		/// <param name="name">Name of the movie</param>
		/// <param name="director">Director of the movie</param>
		/// <returns>IList&lt;Movie&gt;</returns>
        [ResponseType(typeof(IList<Movie>))]
        [HttpGet]
        [Route("search")]
        public virtual IHttpActionResult GetBase([FromUri] string name,[FromUri] string director)
        {
            // Do not modify this code
                        return  ((ISearchController)this).Get(name,director);
                    }
    }
}
