#%RAML 1.0
title: Contacts app

uses:
  Aux: auxiliar.raml

types:
  Contact:
    type: object
    properties:
      name:
        type: string
      gender:
        type: Aux.Gender
    example:
      name: John
      gender: Male
/contacts:
  get:
    responses:
      200:
        body:
          application/json:
            type: Contact
