pipeline {

    agent {
        node {
            label 'windows10'
            customWorkspace 'c:\\cp'
        }
    }
    stages {
        stage('Build'){
            steps {
                bat "dotnet restore src/core-apiexplorer/RAML.NetCoreAPIExplorer.sln"
                bat "dotnet build src/core-apiexplorer/src/RAML.NetCoreAPIExplorer/RAML.NetCoreAPIExplorer.csproj"
                bat "dotnet build src/core-apiexplorer/src/RAML.NetCoreAPIExplorer.Tests/RAML.NetCoreAPIExplorer.Tests.csproj"
            }
        }
        stage('Test'){
            steps{
                bat 'dotnet test src/core-apiexplorer/src/RAML.NetCoreApiExplorer.Tests/RAML.NetCoreApiExplorer.Tests.csproj'
            }
        }
        stage('Pack & Publish'){
            steps {
                bat "dotnet pack src/core-apiexplorer/src/RAML.Parser.Expressions/RAML.Parser.Expressions.csproj"
                bat "dotnet pack src/core-apiexplorer/src/RAML.NetCoreAPIExplorer/RAML.NetCoreAPIExplorer.csproj"
                bat "cp -r src/core-apiexplorer/src/RAML.NetCoreAPIExplorer/bin/Debug/* ./"
                withCredentials([string(credentialsId: 'dotnet-nuget-key', variable: 'NugetApiKey')]) {
                    bat "nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -NoSymbols -SkipDuplicate -ApiKey $NugetApiKey"
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts '*.nupkg'
            archiveArtifacts 'src/core-apiexplorer/src/RAML.NetCoreApiExplorer/bin/Debug/*.nupkg'
        }
        cleanup {
            cleanWs()
        }
    }
}
