#%RAML 1.0 NamedExample
value: |
  {
    "customerId" : "1",
    "status": "Draft",
    "orderItems": [
      {
        "orderItemId": "1",
        "productId": "1",
        "location" : {
          "locationId": "1",
          "locationType": "STORE",
          "deliveryMethod": "PICKUP"
        },
        "price": "40", 
        "productName": "Supersonic Electronic",
        "quantity": 4
      }
    ]  
  }